<?php
/**
 * apiBase 相当于 API模块下的公告 控制器 如果不需要登录场景集成我们这个控制器
 * 那么如果需要登录场景 那他需要集成AuthBase
 * Created by singwa
 * User: singwa
 * motto: 现在的努力是为了小时候吹过的牛逼！
 * Time: 12:26
 */
namespace app\api\controller;

use app\BaseController;
use think\exception\HttpResponseException;

class ApiBase extends BaseController {

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function show(...$args) {
        throw new HttpResponseException(show(...$args));
    }
}